# command: run-pizza-cutter-sims --config ref_config.yaml --seed=42 --n-sims=10000 --backend=loky

shear:
  scene: True

  # these keys are used to build paired sims w/ noise cancellation
  g: 0.02
  swap12: False

  # set these to run a sim directly
  g1: 0.02
  g2: 0.00

msk:
  cosmic_rays: False
    # mean_cosmic_rays: 1
    # min_length: 10
    # max_length: 30

  bad_columns: False
    # mean_bad_cols: 1
    # widths: [1, 2, 5, 10]
    # p: [0.8, 0.1, 0.075, 0.025]
    # min_length_frac: [1, 1, 0.25, 0.25]
    # max_length_frac: [1, 1, 0.75, 0.75]
    # gap_prob: [0.30, 0.30, 0, 0]
    # min_gap_frac: [0.1, 0.1, 0, 0]
    # max_gap_frac: [0.3, 0.3, 0, 0]

  streaks: False
    # mean_steaks: 1
    # min_width: 2
    # max_width: 10

coadd:
  central_size: 225
  buffer_size: 25
  scale: 0.263

se:
  n_images: 1
  wcs_config:
    position_angle_range: [0, 0]
    dither_scale: 0  # set to an odd number of pixels
    scale: 0.263
    scale_frac_std: 0.0
    shear_std: 0.00

psf:
  type: galsim.Gaussian
  fwhm: 0.9
  fwhm_frac_std: 0.0
  shear_std: 0
  shear: [0, 0]

layout:
  type: hex
  ngal_per_side: 10
  ngal_per_arcmin2: 60
  dither_scale: 0.263

gal:
  type: exp-super-bright

star:
  dens_factor: 1
  interp:
    skip: False
    # these control how the interpolation is applied for star holes
    # if fill_isolated_with_noise is True, then any missing pixel with no non-missing
    # pixels within iso_buff will be filled with noise and then used to interpolate
    # the rest of the pixels.
    iso_buff: 1
    fill_isolated_with_noise: True
  apodize:
    skip: True
    ap_rad: 1
  mask_expand_rad: 16

pizza_cutter:
  skip: True
  single_epoch_config:
    # pixel spacing for building various WCS interpolants
    se_wcs_interp_delta: 10
    coadd_wcs_interp_delta: 25
    frac_buffer: 1.42  # buffer around SE image to account for position angle rotations

    reject_outliers: False
    symmetrize_masking: True
    copy_masked_edges: False
    max_masked_fraction: 0.1
    edge_buffer: 8
    mask_tape_bumps: False

    # set the interp flags to 0 or 3 or 7 to interp stuff in the mask
    spline_interp_flags:
      - 7
    noise_interp_flags:
      - 0

    # always zero
    bad_image_flags:
      - 0

metadetect:
  metacal:
    psf: fitgauss
    types: [noshear, 1p, 1m, 2p, 2m]
    use_noise_image: True

  psf:
    lm_pars:
      maxfev: 2000
      ftol: 1.0e-05
      xtol: 1.0e-05
    model: gauss

    # we try many times because if this fails we get no psf info
    # for the entire patch
    ntry: 10

  sx:

  weight:
    fwhm: 1.2  # arcsec

  meds:
    box_padding: 2
    box_type: iso_radius
    max_box_size: 64
    min_box_size: 32
    rad_fac: 2
    rad_min: 4

  maskflags: 33554432  # 2**25 = BMASK_GAIA_STAR from pizza cutter

  # check for an edge hit
  bmask_flags: 1610612736  # 2**29 || 2**30
